### ISSUE TITLE
Pesquisar sobre o funcionamento de CLP's

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#1]

**Comment by Fragata7** [comment]
O Controlador Programável, como todo sistema microprocessado, tem seu princípio de funcionamento baseado nos seguintes passos:
![imagem1](https://user-images.githubusercontent.com/34772965/34569111-1dd86e28-f13e-11e7-8452-45d6fa8da4df.png)

1.**Inicialização**: No momento em que é ligado o CLP executa uma série de operações pré-programadas, gravadas em seu Programa Monitor:
- Verifica o funcionamento eletrônico da C.P.U. , memórias e circuitos auxiliares;
- Verifica a configuração interna e compara com os circuitos instalados;
- Verifica o estado das chaves principais (RUN/STOP, PROG, etc);
- Desativa todas as saídas;
- Verifica a existência de um programa de usuário;
- Emite um aviso de erro caso algum dos itens acima falhe.

2.**Verificar estado das entradas**: O CLP lê o estado de cada uma das entradas, verificando se alguma foi acionada. O processo de leitura recebe o nome de Ciclo de Varredura (Scan) e normalmente é de alguns microssegundos (scan time).

3.**Tranferir os dados para memória**: Após o Ciclo de Varredura, o CLP armazena os resultados obtidos em uma região de memória chamada de Memória Imagem das entradas e saídas. Ela recebe este nome por ser um espelho do estado das entradas e saídas. Esta memória será consultada pelo CLP no decorrer do processamento do programa do usuário.

4.**Comparar com o programa do usuário**: O CLP ao executar o programa do usuário, após consultar a Memória Imagem das Entradas, atualiza o estado da Memória Imagem das Saídas, de acordo com as instruções definidas pelo usuário em seu programa.

5.**Atualizar as saídas**: O CLP escreve o valor contido na Memória das Saídas, atualizando as interfaces ou módulos de saída. Inicia - se então, um novo ciclo de varredura.

**Comment by hyperiondeimos** [comment]
Será ministrado uma aula prática disso na semana que vêm.
