### ISSUE TITLE
Pesquisar no mercado sistemas correlatos ao do projeto

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#13]

**Comment by Fragata7** [comment]
@eliasnoronha @DavidCruzz @dannielalvess @mattcampelo @Wfelipe7 quem pode ficar responsável por essa atividade?

**Comment by DavidCruzz** [comment]
@hyperiondeimos Boa Noite, segue alguns exemplos de sistemas correlatos ao do projeto.

*Envasadora de água mineral*
https://www.youtube.com/watch?v=EI9P2Rw46fI

*Envasadora de cachaça com lavadora de garrafas, recravadora e rotuladora - Empresa Aplimaquinas*
https://www.youtube.com/watch?v=A-5Ywlqrmug

Site: http://www.aplimaquinas.com.br/

*Enchedora de cerveja automática 8 bicos.*
https://www.youtube.com/watch?v=BM2oBZrZpQs
*Empresa JulioEnvase*

- Envasadora Automática - ENA-081
http://www.julioenvase.com.br/2014/05/envasadora-automatica-ena-081.html

- Envasadora Automática - ENA-104
http://www.julioenvase.com.br/2014/05/envasadora-automatica-ena-104.html

**Comment by tassilacassin** [comment]
https://www.youtube.com/watch?v=Efk3X78nSNQ

**Comment by tassilacassin** [comment]
https://www.youtube.com/watch?v=IyeA51VzrAo

**Comment by tassilacassin** [comment]
https://www.youtube.com/watch?v=bj-SENhpmqM
