### ISSUE TITLE
Fazer uma análise da efecácia dos sistemas do mercado

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#14]

**Comment by DanielleAraujo** [comment]
No mercado, temos esteiras bem mais avançadas, com sistemas bem mais aprimorados, como pode-se ver nas imagens a seguir:

![167864-9552485](https://user-images.githubusercontent.com/34780336/35658967-33bbfc62-06da-11e8-8688-1486e3bf07a1.jpg)

![control-systems](https://user-images.githubusercontent.com/34780336/35659218-6e5f8324-06db-11e8-9c6a-f7f9df66c577.jpg)

![forzan-esteira-transportadora-seletora-esteira-transportadora-seletora-forzan-1152500-fgr](https://user-images.githubusercontent.com/34780336/35659223-72302bb6-06db-11e8-935f-8a2bb9799195.jpg)

O principal ponto positivo dos sistemas que estão em operação no mercado, é a eficiência na hora de selecionar os produtos e despachar, são de alta performance.

**Comment by tassilacassin** [comment]
Realiza processos de envase com  precisão, atendendo a um grande número de produtos e embalagens, garantindo alta qualidade e rapidez operacional.

A linha de envase é uma linha de produção especializada em inserir o produto produzido em
uma etapa anterior do processo de fabricação num recipiente, que será o produto final para o
consumidor; este depois deverá ser embalado em sua unidade logística e por fim é paletizado
para posterior armazenagem no depósito 
Uma linha, pode haver de uma a quatro pessoas operado-a, tudo dependerá do grau de automação do equipamento. Essa decisão ocorrerá se a indústria tiver uma demanda suficientemente grande que compense investir em automação para aumentar a produtividade, já que o investimento tem um custo alto e se o volume de produção não for grande o retorno do capital investido pode ser muito demorado causando problemas relacionados ao retorno do investimento realizado.
Cabe ao programador de PCP (Planejamento e Controle da Produção) estar alinhado com a
equipe de supervisão da produção para evitar a concentração dos gargalos em um determinado
período e também não deixar os níveis de estoque de produto acabado muito baixo. 

Informações retiradas do artigo REDUÇÃO DE SET-UP EM LINHAS DE
ENVASE DE LÍQUIDOS: UM ESTUDO DE
CASO

**Comment by tassilacassin** [comment]
Analise da eficacia do CLP no mercado 
estudo feito no site blog da engenharia moderna (controlador logico programável a escolha certa para sua industria) 

Os PLCs são necessários para a sua fabricação?
As aplicações normais de automação de fábrica para as quais os PLCs foram projetados envolvem a fabricação/montagem de itens específicos. Essas aplicações envolvem uma ou mais máquinas e muito movimento de material. Normalmente, estes tipos de processos são monitorados por um operador que observa a progressão através da linha de fabricação. Estes processos são altamente controlados de forma lógica e exigem alta velocidade, o que é muitas vezes controlado por PLCs e pela Interface de combinação Homem-Máquina (HMI). 
Para a fabricação sob demanda do produto, onde a fabricação não é contínua, onde são permitidas interrupções adequadas para a manutenção, solução de problemas ou atualizações que possuem pouco impacto sobre a produção, o pedido é a aplicação do PLC.

 Os PLCs garantiram seu espaço em indústrias de automação com a sua taxa de produção de alta velocidade e flexibilidade de sistema. Estão no mercado há um bom tempo, mas ainda encontram-se em desenvolvendo em ferramentas potentes para todos os tipos de aplicação industrial.
