### ISSUE TITLE
Comparação entre o sensor capacitivo e indutivo

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#16]

**Comment by dannielalvess** [comment]
Esse passo ainda não é possível fazer porque o grupo ainda não decidiu se irá usar visão computacional ou sensores para detectar o nível da água, ainda falta fazer uma comparação de qual seria mais viável.

**Comment by mattcampelo** [comment]
@ vamos fazendo por partes mano, pelo menos o que já sabemos que com certeza terá.
ex: CLP.

**Comment by Fragata7** [comment]
Exato, a tecnologia utilizada será o CLP, a comparação fizemos com professor  sugerimos visão computacional, mas após algumas orientações percebemos que devido a conhecimento e tempo a tecnologia mais viável seria o uso do CLP

**Comment by dannielalvess** [comment]
Segue em anexo uma comparação entre o sensor capacitivo x sensor indutivo, onde se pode concluir que o sensor capacitivo é o melhor para nosso projeto por ter uma alta precisão.
[Sensor Capacitivo.docx](https://github.com/Fragata7/CQdeGarrafas/files/1604274/Sensor.Capacitivo.docx)

**Comment by hyperiondeimos** [comment]
Vão utilizar os seguintes materiais:

![img_20180105_092414956_hdr](https://user-images.githubusercontent.com/6139272/34614344-87744536-f207-11e7-842e-d4d43f8cb582.jpg)
![img_20180105_092418278](https://user-images.githubusercontent.com/6139272/34614345-87a57caa-f207-11e7-951a-3bacfc0a5dd3.jpg)

Me avisem quais desses materiais vocês precisam que eu arranje.
