### ISSUE TITLE
Fazer uma planilha de custo do material utilizado

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#17]

**Comment by eliasnoronha** [comment]
Essa planilha de custos ainda não é a definitiva, mas uma planilha parcial de equipamentos a serem utilizados no projeto, portanto no desenvolvimento do projeto irão ser acrescentados novos materiais  levando em consideração os softwares usados para visão computacional

**Comment by eliasnoronha** [comment]
[planilha de custos.xlsx](https://github.com/Fragata7/CQdeGarrafas/files/1604289/planilha.de.custos.xlsx)

**Comment by DavidCruzz** [comment]
Boa noite, segue em anexo a nova planilha de custo do nosso projeto.
[Controle de Qualidade de máquina envasadora de Garrafas.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1605563/Controle.de.Qualidade.de.maquina.envasadora.de.Garrafas.pdf)

**Comment by hyperiondeimos** [comment]
Incompleto, precisa redefinir o que será utilizado no projeto. Precisa fazer o review meeting para determinar como será o modelo do projeto/maquete.

**Comment by Fragata7** [comment]
![img_20180105_092414956_hdr](https://user-images.githubusercontent.com/34772965/34614635-7ff4e71a-f208-11e7-8aa8-7f723f60348f.jpg)
![img_20180105_092418278](https://user-images.githubusercontent.com/34772965/34614636-80218afe-f208-11e7-8d68-782d2285a669.jpg)

**Comment by DavidCruzz** [comment]
Boa tarde, Segue em anexo a correção da planilha de custos.
[Planilha de custos para o projeto.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1607812/Planilha.de.custos.para.o.projeto.pdf)

**Comment by hyperiondeimos** [comment]
Os valores não batem com o que foi visto in loco dentro dessas empresas citadas (eu liguei para elas).

- Motor DC não precisa comprar fora, compre aqui em Manaus mesmo.
- O Raspberry eu comprei já e está chegando ou sexta 12/01 ou segunda 15/01
- Sensor capacitivo está esse preço mesmo na Dexyi? Verifiquem isso, pois eu posso arranjar um se vocês não conseguirem (mas nesse preço está ok para comprarem)
- Na Arduíno manaus só possuem a solenoide de fluxo, não a válvula em si. Vocês precisam de uma válvula para acionamento pneumático e a solenoide dela.
- O resto parece ok.
