### ISSUE TITLE
Determinar as condições de garrafas aprovadas e reprovadas para o CQ

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#18]

**Comment by dannielalvess** [comment]
Segue em anexo um exemplo em pdf de como é determinado as garrafas aprovadas e reprovadas na esteira, no caso usando visão computacional onde uma camera faz esse processo de imagem.
[Uploading controle de garrafas por visão computacional.pdf…]()

**Comment by dannielalvess** [comment]
Segue em anexo um exemplo em pdf de como é determinado as garrafas aprovadas e reprovadas na esteira, no caso usando visão computacional onde uma camera faz esse processo de imagem.
[controle de garrafas por visão computacional.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1630086/controle.de.garrafas.por.visao.computacional.pdf)

**Comment by DanielleAraujo** [comment]
Aqui vão duas pesquisas que podem ser relevantes para o projeto. Não consegui achar pesquisas direcionadas exatamente para as garrafas de 255 ml.
[GESTÃO DA QUALIDADE NO CONTROLE  METROLÓGICO DOS PRODUTOS.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1633300/GESTAO.DA.QUALIDADE.NO.CONTROLE.METROLOGICO.DOS.PRODUTOS.pdf)
[LEGISLAÇÃO PARA EMBALAGEM DE ALIMENTOS.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1633301/LEGISLACAO.PARA.EMBALAGEM.DE.ALIMENTOS.pdf)

**Comment by tassilacassin** [comment]
informações relevantes, retirada de um trabalho com o titulo "INSPEÇÃO INDUSTRIAL ATRAVÉS DE VISÃO COMPUTACIONAL" feito por MAURÍCIO EDGAR STIVANELLO. 

 A visão computacional tem assumido um importante papel na indústria, auxiliando o homem em tarefas repetitivas e insalubres, como a inspeção de produtos. Os sistemas de visão computacional fundamentam-se em diferentes áreas da ciência da computação. 
O mercado consumidor de produtos industrializados está cada vez mais exigente no que diz respeito à qualidade. Pequenos defeitos e imperfeições antes ignorados agora devem ser observados pelos fabricantes, sob o risco de não satisfazerem os consumidores de seus produtos. Este fato tem motivado as indústrias a investirem cada vez mais nos processos de inspeção de qualidade, já que a mesma se tornou um diferencial competitivo. 
Na indústria de bebidas são inspecionadas as garrafas, visando identificar defeitos como tampas e rótulos mal posicionados ou não presentes, volume do líquido incorreto e falhas na marcação de códigos. 
Por se tratar de uma tarefa extremamente repetitiva e que exige um excessivo esforço físico pelo funcionário que a realiza, a inspeção manual acarreta problemas tais como a falta de inspeção em todos os produtos, a falta de precisão nas inspeções e a alta rotatividade desses trabalhadores. Além disso, a efetividade da inspeção humana declina significativamente no decorrer da jornada de trabalho. Os sistemas de inspeção por computador surgem para auxiliar o homem nestas tarefas. Disponíveis em diversas configurações e aplicáveis em diferentes situações industriais, estes sistemas tem como principal objetivo o auxilio ou até mesmo a substituição da visão humana no ambiente industrial. As vantagens de sistemas como estes, quando comparados à inspeção convencional, evidenciam-se ainda mais quando a linha de produção deve ser monitorada em alta velocidade e com precisão. 
Visando difundir a tecnologia e contribuir para a valorização da mão de obra humana, que na opinião do autor deveria ser aplicada em tarefas mais intelectuais, o presente trabalho apresenta a implementação de um protótipo de software para inspeção industrial automatizada. Este protótipo processa imagens capturadas por uma câmera de vídeo, inspecionando os produtos contidos nas mesmas através da análise de determinadas propriedades, baseando-se em parâmetros previamente definidos. Para realizar tal tarefa foram utilizadas diversas técnicas de processamento de imagens. Também foi utilizada uma rede neural do tipo perceptron multicamada para o reconhecimento e interpretação.
1.1 OBJETIVOS DO TRABALHO
O objetivo deste trabalho é disponibilizar um sistema que processe e analise imagens de produtos de uma linha de produção.
Os objetivos específicos do trabalho são:
a) analisar características como forma, posição e orientação de embalagens plásticas
(frascos) utilizadas na indústria;
b) classificar as embalagens dentre as classes aprovada e rejeitada;
c) detectar defeitos nas embalagens, como a falta ou posição incorreta dos
componentes que a constituem. 

O sistema de descarte é responsável por retirar a peça rejeitada da linha de produção. Comandados pelo software de inspeção, estes sistemas podem assumir diferentes configurações. Muitos destes sistemas utilizam-se de guias para realizar o descarte da peça 
o software de inspeção comanda o sistema de descarte, que redireciona a garrafa rejeitada para outro destino, dentro da linha de produção.
