### ISSUE TITLE
Conhecer o modelo de CLP Zelio SR3 B261 FU

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#2]

**Comment by mattcampelo** [comment]
[video sobre clp zelio](https://www.youtube.com/watch?v=ALQbXdxBW1o&list=PL_bTPvVh_ekb8Msx_65q2ksXSIeaUmD0x)
  
o modelo é diferente do nosso, porém os conceitos são os mesmos.
Abaixo é a foto do nosso CLP.
  
![foto do nosso CLP ZELIO que iremos usar](https://user-images.githubusercontent.com/35061095/34566476-1db9edbc-f135-11e7-9f79-a65ff3a99360.png)

**Comment by mattcampelo** [comment]
Abaixo arquivos em PDF sobre **características,** **manual do usuário,** **guia de programação do zelio** **e exemplos de aplicação.**

- [**Manual do usuário**](http://download.schneider-electric.com/files?p_Reference=EIO0000002695&p_EnDocType=User%20guide&p_File_Id=8448563155&p_File_Name=EIO0000002695.01.pdf)
- [**Guia de programação**](http://download.schneider-electric.com/files?p_Reference=EIO0000002617&p_EnDocType=User%20guide&p_File_Id=8448541112&p_File_Name=EIO0000002617.01.pdf)
- [**Exemplos de aplicações**](http://download.schneider-electric.com/files?p_Reference=EIO0000002605&p_EnDocType=User%20guide&p_File_Id=8449338144&p_File_Name=EIO0000002605.00.pdf)

**Comment by hyperiondeimos** [comment]
Primeiro vocês devem programar nele antes de afirmarem que conhecem o CLP.

**Comment by mattcampelo** [comment]
Vou adicionar algumas informações relevantes que estão no datasheet da schneider sobre o CLP Zelio SR3B261FU.

tempo de ciclo: 6 ~90 ms.
tensão de alimentação: 100 ~240V.
frequência de alimentação: 50 ~60Hz
corrente de aimentação: 80 mA em 100 V
                                      60 mA em 240 V 
                                      50 mA em 240 V 
                                     100 mA em 100 V 
número de entradas: 16.
número de saídas: 10.
tempo de resposta: 50ms.

**Comment by Fragata7** [comment]
@hyperiondeimos  Modelo de programação para ser aplicado no sistema

![programacao em ladder](https://user-images.githubusercontent.com/34772965/35457554-b6845b00-02af-11e8-90e2-e431b7142659.png)

**Comment by Fragata7** [comment]
Segue alguns arquivos modelos usados inicialmente para aplicação no trabalho

[Ladder](https://drive.google.com/open?id=1KZDcNphmZbYfJANShO78E40EeeEro7ns)
