### ISSUE TITLE
Estudar sobre o scrum e aprender a proposta dessa ferramenta

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#20]

**Comment by DanielleAraujo** [comment]
## **Estudo da ferramenta Scrum**

É um framework de gerenciamento de projetos complexos.

O projeto é declarado complexo, dependendo de uma relação de requisitos e tecnologias.

Conforme temos menos conhecimento dos requisitos e a tecnologia, fica mais complexo. Então, entramos em um estado caótico que é um momento propício para a aplicação do scrum.

**3 pilares fundamentais:**

- Transparência

- Inspeção 

- Adaptação


Adaptar o processo do scrum a realidade da empresa.

**Papéis**

Não há scrum sem estes itens a seguir:

- Product Owner: Responsável pelo Product Backlog;

- Scrum Master: Agir como Coach, facilitador;

- Dev team: Pessoas que vão trabalhar para realizar os pedidos do Product Owner.

**Eventos**

- Sprint Planning;

- Execução Sprint;

- Daily Scrum;

- Revisão Sprint;

- Retrospectiva Sprint;

**Artefatos**

- Product backlog;

- Sprint backlog;

- Incremento/ entrega.

As tarefas, dentro do Product backlog, são classificadas por grau de relevância (do menor para o maior).

As sprints têm que ter uma duração fixa.

Antes de iniciar uma sprint, é necessário fazer uma revisão. Isto é chamado de Sprint Planning.

**Burndown chart**
Este faz uma relação entre os Itens a fazer e o Tempo.

**Também temos** 

- Kamban Board;

- Sprint review;

- Retrospectiva.

**Por fim...**
Para realizar as atividades com excelência, é necessário de 2 a 4 semanas para cada sprint.

**Comment by Fragata7** [comment]
De fato o scrum é uma ferramenta valiosa no gerenciamento de projetos, o comentário da @DanielleAraujo foi bem objetivo na sua descrição.
gostaria somente enfatizar outra ferramenta muito útil e que não faz parte do scrum, mas foi citado no comentário anterior, o burndown. A imagem ilustra como o Burndown se aplica nesse projeto
![eddwdw](https://user-images.githubusercontent.com/34772965/35493045-dc889432-0486-11e8-9127-b71bf6bb733a.png)
Podemos observar que nessa sprint as tarefas foram acumuladas logo deixando a linha de trabalho acima da linha linear de aceitação de desenvolvimento da sprint que por recomendação deve está sempre abaixo, mas a equipe entregou as issues no prazo fazendo então que a linha de trabalho ficasse a abaixo da linha linear de aceitação.
A figura a seguir ilustra o andamento das tarefas da sprint 2
![dxsax](https://user-images.githubusercontent.com/34772965/35493164-b3dbb5c2-0487-11e8-98cc-ac232f15b543.png)
Podemos observar que o rendimento das atividades não está adequado, vale ressaltar que o tempo aconselhável para o desenvolvimento de uma sprint fica entre 2 a 4 semanas dependendo do grau de complexidade das tarefas.

Para concluir o burndown vem como outro recurso importante para gerenciar o bom andamento das atividades nas quais foram estipuladas e consequentemente obter êxito nos objetivos
