### ISSUE TITLE
Fazer um levantemos dos recursos pneumatico disponiveis 

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#22]

**Comment by dannielalvess** [comment]
até agora da parte pneumatica só foi utilizado uma valvula 5/2 vias, um atuador pneumatico, mangueiras pneumaticas e compressor. E temos todo esse material disponivel.

**Comment by eliasnoronha** [comment]
- VALVULA 5/2 VIAS 
-ATUADOR PNEUMATICO 2 VIAS
-MANGUEIRAS PU-6 
-MANGUEIRAS PU-8
-ENGATE RAPIDO PARA PU-6
-COMPRESSOR DE DIAFRAGMA
-VALVULA PARA ENCHIMENTO DA GARRAFA(VALVULA NF)
