### ISSUE TITLE
Desenvolver a simulação por software do circuito pneumático

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#23]

**Comment by Fragata7** [comment]
@eliasnoronha @DavidCruzz @dannielalvess @mattcampelo @Wfelipe7 quem pode ficar responsável por essa atividade?

**Comment by Wfelipe7** [comment]
Segue em  anexo a simulação no  FluidSim
https://drive.google.com/file/d/14HdusuOGeVxMESS10MiIIFXq1xUTIEHl/view

**Comment by Wfelipe7** [comment]
Segue em anexo a simulação no FluidSim
https://drive.google.com/file/d/17dhKXevv12kDxNw8phFAsQcytoMjmJbg/view

**Comment by Wfelipe7** [comment]
Segue em anexo a simulação no FluidSim
https://drive.google.com/file/d/17dhKXevv12kDxNw8phFAsQcytoMjmJbg/view

**Comment by dannielalvess** [comment]
Segue em anexo o circuito pneumático com CLP, o circuito pneumático foi desenvolvido no programa Automation Studio 5.2
![diagrama pneumatico](https://user-images.githubusercontent.com/34817709/35488820-5493315e-046d-11e8-8a80-d648ceb53dd7.png)

**Comment by dannielalvess** [comment]
Segue em anexo o circuito pneumático com CLP, o circuito pneumático foi desenvolvido no programa Automation Studio 5.2

![diagrama pneumatico](https://user-images.githubusercontent.com/34817709/35488831-8dfff81e-046d-11e8-8c11-1d9dc211e18c.png)

**Comment by dannielalvess** [comment]
Segue em anexo o arquivo do programa utilizado

**Comment by dannielalvess** [comment]
segue em anexo o arquivo do programa utilizado

https://drive.google.com/open?id=1H1YmuRjSN2l9ccCGQkv-c4g1FE1nBff8

**Comment by dannielalvess** [comment]
Agora falta incluir essa parte pneumatica com o resto da programação

**Comment by hyperiondeimos** [comment]
faltou o da válvula NF (de agua)
