### ISSUE TITLE
Desenvolver um passo a passo de maneria clara, para obter êxito 

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#25]

**Comment by DanielleAraujo** [comment]
A seguir, está mostraremos um fluxograma em blocos e outro feito por meio de Rede de Petri:

![fluxograma](https://user-images.githubusercontent.com/34780336/35762347-8162c7b0-086b-11e8-9d45-cf19a467048f.jpg)

![rede de petri esteira](https://user-images.githubusercontent.com/34780336/35762348-81907840-086b-11e8-97ac-1ad815c20c7e.jpg)

**Comment by hyperiondeimos** [comment]
Poderia simular via flexsim ou arena, mas como eu não passei essa informação para vocês, deixa assim mesmo.
