### ISSUE TITLE
Fazer a revisão desse método corrigindo as falhas se necessário 

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#26]

**Comment by dannielalvess** [comment]
Inicialmente a ideia era fazer uma esteira de 2 metros e utilizar um motor de 24 V para descolar uma garrafa de 2 L. Mas o professor considerou isso desnecessário e fez uma observação que o motor não teria força suficiente para movimentar a esteira. A ideia seguinte foi fazer uma nova esteira com apenas 30 cm e um motor de 12V e utilizar garrafas de 250 ml, e assim, economizamos o principal, tempo. O protótipo da esteira já está em funcionamento, amanhã será anexado imagens.

**Comment by dannielalvess** [comment]
E se possível amanhã será anexado imagens da esteira em funcionamento com os sensores e a câmera...

**Comment by DanielleAraujo** [comment]
Como dito pelo colega @dannielalvess no comentário acima, inicialmente a ideia era montar uma esteira com dimensões maiores, como podemos ver nas fotos a seguir:

![img_20180119_145010670](https://user-images.githubusercontent.com/34780336/35658585-6bba9c9c-06d8-11e8-86a8-3a51393facca.jpg)
![img_20180119_150015135](https://user-images.githubusercontent.com/34780336/35658586-6be6c236-06d8-11e8-8b5e-5a70c63ac022.jpg)

Contudo, não estava sendo viável, pois após a montagem, não obtivemos o resultado esperado. Então, fomos instruídos a mudar de esteira. 
A seguir, serão apresentadas fotos da montagem inicial da segunda esteira:

![whatsapp image 2018-01-26 at 15 41 41](https://user-images.githubusercontent.com/34780336/35658652-c2f9c762-06d8-11e8-8efa-59b5738a6f04.jpeg)
![whatsapp image 2018-01-26 at 15 41 48](https://user-images.githubusercontent.com/34780336/35658653-c32c3fa8-06d8-11e8-99a3-ba1a93a428d6.jpeg)
![whatsapp image 2018-01-26 at 15 41 52](https://user-images.githubusercontent.com/34780336/35658654-c355d0d4-06d8-11e8-91eb-64dd8c5190b0.jpeg)

Serão acrescentadas mais fotos dos aprimoramentos realizados.

**Comment by dannielalvess** [comment]
E por fim, o trabalho foi apresentado sem a parte de analise da garrafa, com visão computacional. Foi apresentado apenas com a enchedora e o atuador que empurrava a garrafa independente do nível. Abaixo segue em anexo imagens do projeto final...

**Comment by dannielalvess** [comment]
![whatsapp image 2018-02-04 at 05 23 52](https://user-images.githubusercontent.com/34817709/35775683-694e94ea-096c-11e8-862a-2c921484ea26.jpeg)
![whatsapp image 2018-02-04 at 05 23 57 1](https://user-images.githubusercontent.com/34817709/35775684-69755116-096c-11e8-85e1-a478653042ab.jpeg)
![whatsapp image 2018-02-04 at 05 23 57](https://user-images.githubusercontent.com/34817709/35775685-69e2ac2a-096c-11e8-8f4d-957e3e545b05.jpeg)

**Comment by dannielalvess** [comment]
![whatsapp image 2018-02-04 at 05 32 50](https://user-images.githubusercontent.com/34817709/35775716-f724b1aa-096c-11e8-8f3a-65e1c15036e4.jpeg)

**Comment by hyperiondeimos** [comment]
Ficou bom
