### ISSUE TITLE
Pesquisar artigos com aplicações de CLP's voltadas para a proposta do projeto

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#3]

**Comment by dannielalvess** [comment]
Esse é uma monografia voltado para a proposta do projeto, que no caso é um controlador de nível tambem.
[monografia.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1604327/monografia.pdf)

**Comment by Fragata7** [comment]
Segue em anexo a revisão sistemática
[Revisão Sistemática_FINAL.docx](https://github.com/Fragata7/CQdeGarrafas/files/1608806/Revisao.Sistematica_FINAL.docx)

**Comment by Fragata7** [comment]
Segue todos os artigos selecionados
[Artigo10.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1608811/Artigo10.pdf)
[Artigo11.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1608812/Artigo11.pdf)
[Uploading Artigo12.pdf…]()
[Uploading Artigo13.PDF…]()
[Uploading Artigo14.pdf…]()
[Uploading Artigo15.pdf…]()
[Uploading Artigo16.pdf…]()
[Uploading Artigo17.pdf…]()
[Uploading Artigo18.pdf…]()
[Uploading Artigo19.pdf…]()
[Uploading Artigo1.pdf…]()
[Uploading Artigo2.pdf…]()
[Uploading Artigo3.pdf…]()
[Uploading Artigo4.pdf…]()
[Uploading Artigo5.pdf…]()
[Uploading Artigo6.pdf…]()
[Uploading Artigo7.pdf…]()
[Uploading Artigo8.pdf…]()
[Uploading Artigo9.pdf…]()

  @hyperiondeimos os artigos estão acima

**Comment by Fragata7** [comment]
@hyperiondeimos as atividades pendentes já estão em review

**Comment by hyperiondeimos** [comment]
Faltou carregar os artigos para eu ler... reabrir

**Comment by Fragata7** [comment]
[Artigo1.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629399/Artigo1.pdf)
[Artigo2.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629400/Artigo2.pdf)
[Artigo3.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629402/Artigo3.pdf)
[Artigo4.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629403/Artigo4.pdf)
[Artigo5.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629404/Artigo5.pdf)
[Artigo6.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629405/Artigo6.pdf)
[Artigo7.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629406/Artigo7.pdf)
[Artigo8.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629407/Artigo8.pdf)
[Artigo9.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629408/Artigo9.pdf)
[Artigo10.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629409/Artigo10.pdf)
[Artigo11.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629410/Artigo11.pdf)
[Artigo12.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629411/Artigo12.pdf)
[Artigo13.PDF](https://github.com/Fragata7/CQdeGarrafas/files/1629412/Artigo13.PDF)
[Artigo14.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629413/Artigo14.pdf)
[Artigo15.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629414/Artigo15.pdf)
[Artigo16.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629415/Artigo16.pdf)
[Artigo17.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629416/Artigo17.pdf)
[Artigo18.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629417/Artigo18.pdf)
[Artigo19.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629418/Artigo19.pdf)
@hyperiondeimos Os artigos publicados

**Comment by hyperiondeimos** [comment]
ok
