### ISSUE TITLE
Definir qual a melhor linguagem de CLP para desenvolver o projeto

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#31]

**Comment by Fragata7** [comment]
Programação Ladder

A programação em ladder é a mais usada em CLP's, cada tarefa é especificada como degraus de uma escada (ramo), esse tipo de linguagem é representada graficamente, a dinâmica da lógica é de diagrama de contatos e se assemelha com à usual notação de diagramas elétricos.

Diante dos argumentos listados acima a linguagem de programação que será utilizada é a Ladder

A apostila anexada abaixo descreve o funcionamento de CLP's, também sobre a linguagem e outras informações pertinentes ao uso de CLP's o que é de grande relevância para o desenvolvimento do projeto   [ApostilaCLP](https://github.com/Fragata7/CQdeGarrafas/files/1603603/ApostilaCLPFinal.pdf)

**Comment by eliasnoronha** [comment]
[Aula 3 - Projeto de Automacao por SFC.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1604396/Aula.3.-.Projeto.de.Automacao.por.SFC.pdf)
Nesta apostila se aborda de maneira didatica os diversos tipos de programação de um clp bem como suas características.

**Comment by hyperiondeimos** [comment]
Na minha opinião, o GRAFCET não é necessário. O conhecimento pode ser explicado, mas não sei se o SR3 Zelio que vocês tem, contem as instruções para desenvolver algo em SFC. Ladder é mais apropriado.
