### ISSUE TITLE
Treinamento de CLP

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#32]
A equipe solicita um treinamento de CLP com os itens listados abaixo, para desenvolver com êxito o projeto;

- [x] Aprender o que é um CLP

- [x] Funcionamento de um CLP e seus componentes agregados para uso

- [x]  SFC  (Grafect)

- [x] Ladder

- [ ] Supervisiono 

  
  @hyperiondeimos

**Comment by hyperiondeimos** [comment]
Tenho certas duvidas?
Quais equipamentos vocês precisam para mexer no CLP?
E o que você quer dizer com o sistema supervisório? Pois depende da integração de uma linguagem de programação ou de um sistema de IHM, podendo utilizar o ScadaBR também. Preciso de uma definição de vocês para preparar a aula

**Comment by hyperiondeimos** [comment]
Já ministrei a aula. Não passei supervisório pois não dá tempo. Contudo, procurem no Youtube sobre aplicações com Visual Studio e C# com o Arduino.
