### ISSUE TITLE
Revisão do material listado fazendo alterações se necessário 

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#33]

**Comment by eliasnoronha** [comment]
Nesta etapa iremos adicionar mais componentes , que julgamos serem de extrema importancia para o bom andamento do projeto

**Comment by Fragata7** [comment]
@eliasnoronha  @DavidCruzz @dannielalvess @mattcampelo @Wfelipe7 quem pode ficar responsável por essa atividade?

**Comment by Fragata7** [comment]
Para essa primeira parte da construção foram levantados os seguintes materiais :
1 chapa de apoio de metalon de dimensões (1400mmx300mm)
4 perfis de aço de  (2000mmx100mm)
2 tubos de metalon para a rotação da esteira de dimensões 90 mm de diametro x 300mm de comprimento obs: esse item precisa ser verificado pois não se sabe se o material irá suportar a rotação do motor
5 parafusos sextavados 5 mm
5 parafusos sextavados 10 mm
5 parafusos com arruela 10 mm
5 parafusos sextavados 15 mm
5 parafusos de encaixe Philips 10 mm
2 fitas isolantes para proteção das conexões elétricas
1 jogo de braçadeiras de plástico (saco de 1kg) para demais fixações

**Comment by hyperiondeimos** [comment]
Ok, preciso da evidencia disso para fechar está issue. No aguardo.

**Comment by DanielleAraujo** [comment]
![rolete com motor](https://user-images.githubusercontent.com/34780336/35293826-443b0096-004b-11e8-9164-98ed689a708e.jpg)
![chapa de aco e materiais emprestados](https://user-images.githubusercontent.com/34780336/35293827-447245c4-004b-11e8-8a9e-eac85d518842.jpg)
![teste1](https://user-images.githubusercontent.com/34780336/35293828-454ab986-004b-11e8-9e36-7b5339d9ce23.jpg)
![teste2](https://user-images.githubusercontent.com/34780336/35293830-46474e26-004b-11e8-9f0b-f47703eeec08.jpg)

**Comment by Fragata7** [comment]
@hyperiondeimos  A proposta anterior foi substituída, logo os matérias também foram alterados.
segue em anexo as imagens dos matérias que foram emprestados 
![esteira](https://user-images.githubusercontent.com/34772965/35457477-7726305a-02af-11e8-99fe-f95dcdfc7ead.jpeg)
      
![estrutura de exemplo](https://user-images.githubusercontent.com/34772965/35457478-774f5e76-02af-11e8-88a2-202e65cc2741.jpeg)
![motor](https://user-images.githubusercontent.com/34772965/35457480-7778360c-02af-11e8-9479-66ff4b9d86b9.jpeg)
![regulador de tensao](https://user-images.githubusercontent.com/34772965/35457482-779df892-02af-11e8-9eea-fdde225cbabd.jpeg)
![sensor 1](https://user-images.githubusercontent.com/34772965/35457483-77c27c76-02af-11e8-9ebb-d1e9b8c30421.jpeg)
![valvula rf](https://user-images.githubusercontent.com/34772965/35457484-77eae846-02af-11e8-93e2-990b28fb2c24.jpeg)
![valvula solenoide](https://user-images.githubusercontent.com/34772965/35457485-7812424c-02af-11e8-92a5-206b3e777af1.jpeg)
![valvulas pneumaticas](https://user-images.githubusercontent.com/34772965/35457486-7839f6a2-02af-11e8-9f2f-e93f30f7e5f6.jpeg)
![correia](https://user-images.githubusercontent.com/34772965/35457487-786444de-02af-11e8-9c64-ce30533056df.jpeg)
