### ISSUE TITLE
Revisão da tabela de custos, fazendo alterações se necessário

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#34]

**Comment by Fragata7** [comment]
@eliasnoronha @DavidCruzz @dannielalvess @mattcampelo @Wfelipe7 quem pode ficar responsável por essa atividade?

**Comment by DavidCruzz** [comment]
Boa noite, segue em anexo a atualização de custos para o projeto.

[Planilha de custo para o projeto - atualizada.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1629880/Planilha.de.custo.para.o.projeto.-.atualizada.pdf)

**Comment by hyperiondeimos** [comment]
Atualizar os dados dos componentes emprestados. NUNCA um atuador de dupla ação da FESTO terá o preço dado. No Raspberry Pi não vi os dados do cartão de memória e da fonte 5V.

Revisar.

**Comment by DavidCruzz** [comment]
Bom Dia, segue em anexo a tabela de custos atualizada.
[Planilha de custo para o projeto - atualizada.pdf](https://github.com/Fragata7/CQdeGarrafas/files/1685479/Planilha.de.custo.para.o.projeto.-.atualizada.pdf)
