### ISSUE TITLE
Concluir a 1º parte da contrução da esteira

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#35]
- [x] Desenho da esteira em qualquer software de CAD

- [x] Definição da metodologia de funcionamento

- [x] Adquirir matérias necessários

- [x] Dar inicio a montagem física da esteria

**Comment by Fragata7** [comment]
As representações dos desenhos a seguir ainda sofrerão alterações para inclusão de suporte para sensores, câmera, atuadores pneumáticos e elementos de fixação mecânica.

[CAD](https://drive.google.com/file/d/1B4lkjC2rZYCP3v_OiqTCbtvF9I-JXiWa/view?usp=sharing)

**Comment by Fragata7** [comment]
A metodologia do funcionamento definida consiste em um sistema que suporte o transporte unidades de garrafas fazendo uma parada momentânea para o envasamento pré estabelecido por uma central de controle, essa parada deve ser condicionada a mudança de estado de um sensor.
Após essa etapa de envasamento a esteira continua transportando a garrafa, passando por uma etapa de filtragem definindo as garrafas que podem teoricamente seguir para lotes aprovados e por consequência setores de almoxarifado ou expedição, e as garrafas que não estiverem dentro da margem de aceitação serão desviadas por um atuador pneumático, para serem envasadas novamente ou passar por outro processo conforme a ordem do CQ.
Tanto funcionamento de transporte da esteira quanto o sistema seletor de garrafas dentro da margem de aceitação pré estabelecida serão controlados por CLP e Raspbery

**Comment by Fragata7** [comment]
Boa parte dos matérias já foram adquirido, os matérias que não foram adquiridos serão listados a seguir

1. Material para a estrutura física da esteira

2. Câmera (webcam)

3. Sensor capacitivo 

4. Válvula Solenoide

5. Atuador pneumático (verificar no laboratório)  

Esses matérias não foram adquiridos por falta de recursos, esperamos da continuidade no processo na próxima sprint.

**Comment by Fragata7** [comment]
A montagem física ficará pra próxima sprint, uma vez que ainda não adquirimos o material

**Comment by Fragata7** [comment]
@hyperiondeimos Solicito auxilio no desenvolvimento dos desenhos em CAD para incluir os elementos de fixação mecânica mais adequados e conforme a norma, e um bizu na animação da esteira com o solidworks... ( rsrsrsrsrs )

**Comment by eliasnoronha** [comment]
para essa primeira parte da construção foram levantados os seguintes materiais :
1 chapa de apoio de metalon de dimensões (1400mmx300mm)
2 perfis de aço de 100mm de espessura 
2 tubos de metalon para a rotação da esteira de dimensões 90 mm de diametro x 300mm de comprimento obs: esse item precisa ser verificado pois não se sabe se o material irá suportar a rotação do motor
5 parafusos sextavados 5 mm
5 parafusos sextavados 10 mm
5 parafusos com arruela 10 mm
5 parafusos sextavados 15 mm
5 parafusos de encaixe phillips 10 mm
2 fitas isolantes para proteção das conexões elétricas
1 jogo de braçadeiras de plastico (saco de 1kg) para demais fixações

**Comment by eliasnoronha** [comment]
Com base na lista anterior foram acrescentados esses materiais para a construção fisica da estrutura

**Comment by hyperiondeimos** [comment]
O que seria necessário no AutoCAD e SolidWorks? Não entendi....

Animação eu já ensinei a todos vocês na disciplina de Projetos com CAD. Já em AutoCAD não é necessário nada. Basta desenhar em 3D o projeto e depois colocar as vistas...

No aguardo do que for preciso.

**Comment by DanielleAraujo** [comment]
Segue as fotos da construção inicial do projeto.
@hyperiondeimos 

![whatsapp image 2018-01-26 at 15 41 41](https://user-images.githubusercontent.com/34780336/35457898-dcf02368-02b0-11e8-9084-64db6155106a.jpeg)
![whatsapp image 2018-01-26 at 15 41 48](https://user-images.githubusercontent.com/34780336/35457899-dd18caca-02b0-11e8-9a28-24a8feb2fa00.jpeg)
![whatsapp image 2018-01-26 at 15 41 52](https://user-images.githubusercontent.com/34780336/35457900-dd43abdc-02b0-11e8-958d-f4d3e343a23d.jpeg)
