### ISSUE TITLE
Desenvolver a programação do sistema CQdeGarrafas

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#36]

**Comment by Fragata7** [comment]
@eliasnoronha @DavidCruzz @dannielalvess @mattcampelo @Wfelipe7 quem pode ficar responsável por essa atividade?

**Comment by Wfelipe7** [comment]
Segue em anexo simulação  em FluidSim
https://drive.google.com/file/d/14HdusuOGeVxMESS10MiIIFXq1xUTIEHl/view

**Comment by hyperiondeimos** [comment]
Mande umas 15 fotos da garrafa cheia do jeito que vocês querem, por favor. Irei pelo menos tentar ajudar no haar cascade (somente).

Recomendo colocar uma placa branca como background para dar contraste no liquido. Lembrando que a garrafa DEVE ser transparente e devemos colocar o sensor capacitivo na posição do liquido.

**Comment by Fragata7** [comment]
@hyperiondeimos [As fotos](https://drive.google.com/drive/folders/1zL2v_zabqIqCAFUvHxKfNOlhVNbAEdps?usp=sharing)

**Comment by hyperiondeimos** [comment]
Já instalaram o OpenCV no raspberry pi? Eu deixei um script automatico para fazer isso de forma facilitada para vocês na pasta do Dropbox - aula 07.

Lembrem que eu já disse que por vocês estarem utilizando o raspberry pi 2, a instalação levará no minimo 10h!!! Então, se der problema com isso, a janela de vocês ficará SUPER pequena.

@Fragata7 ponha alguém para correr com isso logo, quero ver o python, raspbian  e o OpenCV 3 funcionando amanhã já.

**Comment by Fragata7** [comment]
@hyperiondeimos Aparentemente esse processo inicial já foi feito, aguardando o XML para dá continuidade

**Comment by hyperiondeimos** [comment]
Vou postar na aba code

FEITO!

Já testei e funciona.
