### ISSUE TITLE
Materiais para projeto

### ISSUE THREAD

**Issue by DanielleAraujo** [Fragata7/CQdeGarrafas#37]
A todos, precisamos dos seguintes materiais para sexta-feira (18/01/2018): 

- [ ] Cola Super Bonder/ Cola 1000

- [ ] Fita dupla face verde 

- [ ] Broca de ferro pequena (Pelo menos 3 tamanhos)

- [ ] Parafuso e porca (médio e pequeno)

- [ ] Garrafa de água (~250 ml)

- [ ] Arco de serra

- [x] Braçadeira

- [x] Potenciômetro 10k
- [ X] Caixa de durepoxi

**Comment by DanielleAraujo** [comment]
Vou levar o Potenciômetro de 10k. Já marquei na lista.

**Comment by hyperiondeimos** [comment]
Isso ainda não foi finalizado? Status?

**Comment by Fragata7** [comment]
@hyperiondeimos Boa tarde!
Estamos como um problema que o senhor pode resolver bem fácil;
**O problema**: É que o diâmetro da válvula do atuador pneumático para por o cabo de **P.U**  é diferente da válvula solenoide.
 **Solução**: Falei com o Vanio ele libera as válvulas do laboratório desde que o senhor fale com ele.
(obs: Já Compramos cabos P.U só estamos dependendo desse detalhe para começar a testar os atuadores com o CLP.
Gostaríamos do auxilio do senhor na segunda se possível para fazer ligação pneumática com CLP)

obrigado pela atenção!         
![cilindro-pneumatico-01](https://user-images.githubusercontent.com/34772965/35456250-3698862c-02ab-11e8-87e9-9872cffccf07.jpg)

**Comment by hyperiondeimos** [comment]
Mestre @Fragata7, não sei se o Sr. sabe, mas TODAS essas conexões são chamadas de engate rápido e são destacáveis! Não precisa trocar as válvulas para realizar isso, somente precisa comprar os adaptadores de engate rápido. Um adaptador desses deve ser R$ 5,00 e um pedaço de cabo PU-6 não custa R$ 1,00. Exemplos de engates que vocês podem comprar:

1. Conexão em T (8/8/6):

![image](https://user-images.githubusercontent.com/6139272/35462227-781a48ae-02c1-11e8-80ab-e05cb66c247b.png)

2. Conexão Rápida PU-8 com rosca macho 1/4":

![image](https://user-images.githubusercontent.com/6139272/35462255-8f3212a6-02c1-11e8-9e06-b1b05078032e.png)

3. Conexão Simples Push-In PU-8 p/ PU-6:

![image](https://user-images.githubusercontent.com/6139272/35462276-a73f1006-02c1-11e8-9c24-3ee29085b2d9.png)

4. Conexão em Y (8/6/6):

![image](https://user-images.githubusercontent.com/6139272/35462297-bae79808-02c1-11e8-9b8f-8c784e7ba6a4.png)


Somente basta modificar na válvula ou no atuador uma dessas conexões ai de cima.

Não se conecta parte pneumática ao CLP. Apenas se conecta a solenoide. E a solenoide de acionamento é como se fosse um relé com bobina, na maior parte dos casos, de 24VCC. Basta olhar a descrição da solenoide. O fio branco geralmente é o retorno do comum.

Não espere até segunda não, faça isso até amanhã. Quero ver o funcionamento de TODOS os projetos até amanhã (pelo menos montado corretamente).

**Comment by hyperiondeimos** [comment]
Os adaptadores vocês compram nas mesmas lojas que vocês já conhecem (BA Eletrica, Casa do Eletricista, Dexyi, Sunxtronics, Casa das Mangueiras, Rolapeças, entre outros).

**Comment by Fragata7** [comment]
@hyperiondeimos  Ok, vamos providenciar obrigado

**Comment by eliasnoronha** [comment]
[LISTA MATERIAIS.xlsx](https://github.com/Fragata7/CQdeGarrafas/files/1692910/LISTA.MATERIAIS.xlsx)

Segue em anexo lista dos materiais utilizados

**Comment by eliasnoronha** [comment]
[LISTA MATERIAIS.xlsx](https://github.com/Fragata7/CQdeGarrafas/files/1693188/LISTA.MATERIAIS.xlsx)

**Comment by eliasnoronha** [comment]
[LISTA MATERIAIS.xlsx](https://github.com/Fragata7/CQdeGarrafas/files/1693203/LISTA.MATERIAIS.xlsx)
