### ISSUE TITLE
Atividades e WIKI

### ISSUE THREAD

**Issue by DanielleAraujo** [Fragata7/CQdeGarrafas#38]
Iremos fazer: 

- [x] Base da esteira

- [x] Suporte para motor, atuadores e sensores

- [x] Colar esteira

Ao final do dia, marcar aqui o que foi realizado.

**Comment by hyperiondeimos** [comment]
Como está o andamento disso? Fotos e outras infos são bem vindos

**Comment by hyperiondeimos** [comment]
Sobre o problema de ordenação no Wiki. @DanielleAraujo Se baseie neste artigo:

https://stackoverflow.com/questions/39396362/github-wiki-pages-sort-order

Eu coloquei por numeração, mas fica feio. Dê uma olha e aplique a ordenação.

**Comment by DanielleAraujo** [comment]
Pelo menos está na ordem. Obrigada, professor.

2018-01-26 13:31 GMT-04:00 Anderson Gadelha Fontoura <
notifications@github.com>:

**Comment by hyperiondeimos** [comment]
Tente a outra forma passada no fórum por favor.

**Comment by DanielleAraujo** [comment]
Professor, a forma como está sendo passada pelo fórum não está sendo clara.

**Comment by DanielleAraujo** [comment]
Pelo que vejo, enumerar é uma forma mais simples de mantê-lo em ordem.

**Comment by DanielleAraujo** [comment]
@hyperiondeimos , não consigo achar uma forma de acrescentar as imagens. Estou tendo copiar e colar o link, mas a imagem não aparece.

**Comment by hyperiondeimos** [comment]
@DanielleAraujo não consigo entender dá onde você tirá que não está claro. É porque está em inglês?

Ele fala explicitamente para você ir nas paginas:

https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki
e
https://stackoverflow.com/questions/9239588/toc-or-sidebar-in-github-wiki

Para ter uma ideia melhor de fazer a ordenação.

Desculpe, mas eu não acho que o método de numerar é mais bonito do que este aqui:

![image](https://user-images.githubusercontent.com/6139272/35453562-111132fa-02a1-11e8-9a24-17cf20d77fbb.png)

E @DanielleAraujo, tá vendo esse ícone de edição marcado na imagem acima? Basta você acessar e ver como o cara organizou tudo. Mais fácil que isso só empurrando bêbado da ladeira.

Faça bonito, sem mais (é uma ordem).

**Comment by DanielleAraujo** [comment]
@hyperiondeimos  (risos) . Ok, obedecerei. Mas eu não tava entendendo nada mesmo, de verdade.

**Comment by DanielleAraujo** [comment]
@hyperiondeimos  Está ai, como pediu.  


![MISSÃO DADA É MISSÃO CUMPRIDA](https://user-images.githubusercontent.com/34780336/35454484-9b949090-02a4-11e8-9307-030a1ad07df9.jpg)

**Comment by DanielleAraujo** [comment]
À todos os membros do grupo, não tenho acesso aos códigos e imagens do projeto finalizado, portanto, não consigo desenvolver muita coisa no Wiki na parte de Materiais e Métodos/ Resultados e discussões. Peço que joguem essas informações lá.

**Comment by hyperiondeimos** [comment]
Tá ótimo, só faltou as imagens
