### ISSUE TITLE
Pesquisar eventos e congressos nos quais o projeto se enquadra para participação

### ISSUE THREAD

**Issue by Fragata7** [Fragata7/CQdeGarrafas#6]

**Comment by Fragata7** [comment]
1. **CONGRESSO BRASILEIRO DE AUTOMÁTICA**

O Congresso Brasileiro de Automática acontece nos dias 09 a 12 de Setembro de 2018 no Hotel Tropical Tambaú, como uma realização do Departamento de Engenharia Elétrica do Centro de Energias Alternativas e Renováveis (UFPB) e da Sociedade Brasileira de Automática/IFAC.
O evento reúne as comunidades científicas e industriais possibilitando a troca de informações entre os diversos profissionais da área de ciências elétricas. Promove mini-cursos e palestras para atualização de estudantes, docentes, pesquisadores e profissionais. Além de trazer convidados e o que há de mais inovador no mundo da engenharia.
[CONGRESSO BRASILEIRO DE AUTOMÁTICA](http://www.ufpb.br/cba2018/)

2.**REVISTA PRODUÇÃO E ENGENHARIA**

 A Revista Eletrônica Produção e Engenharia foi criada em 2007, como resultado da evolução natural dos trabalhos e atividades desenvolvidos pelo Fórum Mineiro de Engenharia de Produção. A Revista tem como objetivo fomentar a disseminação de conhecimento em Engenharia de Produção, através da publicação de artigos que apresentem conceitos, metodologias e resultados teóricos e práticos que contribuam para o desenvolvimento das empresas, dos profissionais, da sociedade e da produção científica.
    ICCEEg – Revista Jr de Iniciação Científica em Ciências Exatas e Engenharia – destinada à publicação de artigos escritos por acadêmicos de cursos ligados as ciências exatas e engenharia, de acesso livre.
    Revista Anagrama – Universidade São Paulo (USP) – temas relacionados à mídia, imprensa e comunicação social a partir de uma ótica interdisciplinar. A principal meta é divulgar a produção acadêmica dos graduandos de qualquer área do conhecimento. 
[REVISTA PRODUÇÃO E ENGENHARIA](revistaproducaoengenharia.org)

3.**ANAIS DA ACADEMIA BRASILEIRA DE CIÊNCIA** 

 Informações Básicas: A Academia Brasileira de Ciências mantém a publicação trimestral dos Anais da AABC (Anais da Academia Brasileira de Ciência), iniciada regularmente em 1929, a mais antiga revista científica de circulação contínua no país. Este periódico científico, de circulação nacional e internacional, visa publicar avanços na pesquisa científica, tanto de pesquisadores atuantes no país como também de cientistas de outras nacionalidades, atuantes nos principais centros de pesquisa do exterior, tendo como parâmetro a excelência da pesquisa. A sua natureza é multidisciplinar, publicando resultados originais de pesquisas realizadas nas mais diversas áreas da ciência, como matemática, física, química, biológica, biomédica, saúde, sociais, engenharia, agrárias e da Terra. 

Condições de Submissão: Consultar o site da revista [ANAIS DA ACADEMIA BRASILEIRA DE CIÊNCIA](http://www.abc.org.br/article.php3?id_article=100)

4.**OLAM – CIÊNCIA E TECNOLOGIA** 

 Informações básicas: OLAM (Universo em hebraico) - Ciência & Tecnologia publica artigos inéditos de caráter científico com o objetivo de atender diferentes profissionais diante dos vários contextos de estudos e pesquisas ambientais interdisciplinares, contribuindo para a difusão, diálogo e intercâmbio de conhecimentos teóricos ou aplicados, bem como para a formação de redes, envolvendo seguintes eixos temáticos: engenharias, arquitetura & projetos; direito ambiental & urbanístico; direitos humanos; qualidade ambiental, qualidade de vida & saúde ambiental; desenvolvimento de comunidades; economia ambiental; educação ambiental; psicologia social e 

ambiental; percepção, interpretação e valoração do meio ambiente; ecologia de paisagens naturais e construídas; conservação, preservação e valoração do meio ambiente. 

Condições de Submissão: Consultar o seguinte [OLAM – CIÊNCIA E TECNOLOGIA](http://www.olam.com.br/normas.htm)

5.**13th APCA International Conference on Control and Soft Computing (CONTROLO 2018)**

Está aberto a chamada de trabalhos -  Call for Papers para 13th APCA International Conference on Control and Soft Computing [(CONTROLO](url) 2018, http://www.apcacontrolo.org/controlo2018/), que será realizada em Ponta Delgada, Ilha de São Miguel, Açores, Portugal, em 4-6 de junho. 2018.

A conferência é organizada pela Associação Portuguesa de Controlo Automático (APCA), uma organização membro nacional da International Federation of Automatic Control (IFAC). Esta 13ª edição da conferência é um marco especial para a APCA, já que coincide com a celebração do seu 25º aniversário.

**Comment by dannielalvess** [comment]
Segue em anexos outras instituições onde podem ser publicados.
[REVISTAS QUE PODEM SER PUBLICADOS ARTIGOS.docx](https://github.com/Fragata7/CQdeGarrafas/files/1604253/REVISTAS.QUE.PODEM.SER.PUBLICADOS.ARTIGOS.docx)

**Comment by hyperiondeimos** [comment]
3 de 8, falta completar.

**Comment by DavidCruzz** [comment]
**1.CONGRESSO BRASILEIRO DE AUTOMÁTICA**
O Congresso Brasileiro de Automática acontece nos dias 09 a 12 de Setembro de 2018 no Hotel Tropical Tambaú, como uma realização do Departamento de Engenharia Elétrica do Centro de Energias Alternativas e Renováveis (UFPB) e da Sociedade Brasileira de Automática/IFAC.
O evento reúne as comunidades científicas e industriais possibilitando a troca de informações entre os diversos profissionais da área de ciências elétricas. Promove mini-cursos e palestras para atualização de estudantes, docentes, pesquisadores e profissionais. Além de trazer convidados e o que há de mais inovador no mundo da engenharia.
CONGRESSO BRASILEIRO DE AUTOMÁTICA

http://www.ufpb.br/cba2018/

**2.ANAIS DA ACADEMIA BRASILEIRA DE CIÊNCIA**
Informações Básicas: A Academia Brasileira de Ciências mantém a publicação trimestral dos Anais da AABC (Anais da Academia Brasileira de Ciência), iniciada regularmente em 1929, a mais antiga revista científica de circulação contínua no país. Este periódico científico, de circulação nacional e internacional, visa publicar avanços na pesquisa científica, tanto de pesquisadores atuantes no país como também de cientistas de outras nacionalidades, atuantes nos principais centros de pesquisa do exterior, tendo como parâmetro a excelência da pesquisa. A sua natureza é multidisciplinar, publicando resultados originais de pesquisas realizadas nas mais diversas áreas da ciência, como matemática, física, química, biológica, biomédica, saúde, sociais, engenharia, agrárias e da Terra.
Condições de Submissão: Consultar o site da revista ANAIS DA ACADEMIA BRASILEIRA DE CIÊNCIA

http://www.abc.org.br/article.php3?id_article=100

**3.REVISTA IGAPÓ - IFAM**
A IGAPÓ - Revista de Educação, Ciência e Tecnologia do IFAM é uma publicação oficial de divulgação do Instituto Federal de Educação, Ciência e Tecnologia do Amazonas e surgiu da necessidade de divulgar o conhecimento científico-tecnológico produzido, principalmente, por pesquisadores dos diversos cursos do IFAM – Ensino Técnico Integrado ao Médio, Subsequente, Graduação e Pós-Graduação e EJA (PROEJA). Sua periodicidade, a partir de 2011, é semestral. A despeito de poder também publicar números especiais.
**Revista Igapó tem Qualis em diversas áreas no quadriênio 2013-2016**

Ciências ambientais (Qualis C); Química (Qualis C); Sociologia (Qualis C); Zootecnia/Recursos Pesqueiros (Qualis C); Ensino (Qualis B5); Interdisciplinar (Qualis B5) e Materiais (Qualis B4).

[NormasdaRevistaIgapo.pdf]
(https://github.com/Fragata7/CQdeGarrafas/files/1608428/NormasdaRevistaIgapo.pdf)

**5. REVISTA LATINO-AMERICANA DE INOVAÇÃO E ENGENHARIA DE PRODUÇÃO**

http://revistas.ufpr.br/relainep/
A Revista Latino-Americana de Inovação e Engenharia de Produção é uma publicação online de divulgação científica, com periodicidade semestral de acesso livre e gratuito sob a responsabilidade do Programa de Pós-Graduação em Engenharia de Produção da Universidade Federal do Paraná. A revista tem como principal objetivo contribuir para a disseminação da pesquisa no âmbito da Engenharia de Produção na América Latina. A política editorial da revista prioriza trabalhos que tenham aproximações


**6. GEPROS
GESTÃO DA PRODUÇÃO, OPERAÇOES E SISTEMAS**

http://revista.feb.unesp.br/index.php/gepros/about

A Revista Gepros teve o estrato qualis atualizado na Plataforma Sucupira em 2015 e ela está avaliada como B4 na área de Engenharias III e como B3 na Administração.
A Revista GEPROS é um periódico acadêmico publicado em versão eletrônica do Departamento de Engenharia de Produção da Universidade Estadual Paulista (UNESP), Campus Bauru. A Revista GEPROS foi criada em 2009 e desde então está direcionada a professores, pesquisadores, pós-graduandos, graduandos, profissionais e interessados nas áreas de Engenharia de Produção e correlatas. O objetivo da GEPROS é contribuir para a disseminação de conhecimentos classe-mundial na área de Engenharia de Produção, contribuindo tanto para o avanço nas fronteiras do estado-da-arte dos temas que aborda, à luz dos mais elevados padrões acadêmicos, quanto para o desenvolvimento e modernização da sociedade, possuindo intrínseco valor prático.

**7.REVISTA PRODUÇÃO E ENGENHARIA** 

http://www.fmepro.org/ojs/index.php/rpe


       A Revista Eletrônica Produção e Engenharia foi criada em 2007, como resultado da evolução natural dos trabalhos e atividades desenvolvidos pelo Fórum Mineiro de Engenharia de Produção. A Revista tem como objetivo fomentar a disseminação de conhecimento em Engenharia de Produção, através da publicação de artigos que apresentem conceitos, metodologias e resultados teóricos e práticos que contribuam para o desenvolvimento das empresas, dos profissionais, da sociedade e da produção científica.

**8.  ICCEEg**

 (Revista Jr de Iniciação Científica em Ciências Exatas e Engenharia - ISSN 2236-0093) é um periódico semestral de publicação digital destinada à publicação de artigos escritos por acadêmicos de cursos ligados as ciências exatas e engenharia, de acesso livre, visando estimular e disseminar a pesquisa nessas áreas de pesquisa.
 
Em seus quatorze primeiros números, a ICCEEg teve mais de 500 artigos submetidos por autores de diversas regiões do estado e do país. A taxa de aceite de aproximadamente 25% dos artigos submetidos ilustra a alta demanda por periódicos neste formato. Pela classificação da CAPES do quadriênio 2013-2016, o QUALIS da ICCEEg para a área de Engenharias I é B5, e para as áreas de Ciência da Computação, Engenharias IV e Interdisciplinar é C.

http://www.icceeg.c3.furg.br/

**Comment by hyperiondeimos** [comment]
ok, mas alguns links não estão redirecionando para o evento ao qual dizem. Favor consertar.
